[Variables]
TOKEN=1234abcd

; SHORTCUTS
; 1 | 6
; 2 | 7
; 3 | 8
; 4 | 9
; 5 | 10
Text1=Código
Path1="T:"
Text2=Documentos
Path2="V:"
Text3=Fotos
Path3="X:"
Text4=Gráfico
Path4="U:"
Text5=Libros
Path5="Y:"
Text6=Música
Path6="Z:"
Text7=Partituras
Path7="W:"
Text8=Proyectos
Path8="X:"
Text9=Vídeos
Path9="U:"
Text10=Web
Path10="W:"

; LOCAL SHORTCUTS
Image1=#IconsPath#trash.png
Image1Hover=#IconsPath#trash2.png
Image1Text=Papelera de reciclaje
PathImage1="::{645FF040-5081-101B-9F08-00AA002F954E}"
Image2=#IconsPath#documents.png
Image2Hover=#IconsPath#documents2.png
Image2Text=Documentos
PathImage2="C:\Users\orzan\Documents"
Image3=#IconsPath#download.png
Image3Hover=#IconsPath#download2.png
Image3Text=Descargas
PathImage3="C:\Users\orzan\Downloads"
Image4=#IconsPath#target.png
Image4Hover=#IconsPath#target2.png
Image4Text=Wildlands
PathImage4="A:\Juegos\UPlay\Tom Clancy's Ghost Recon Wildlands\GRW.exe"
Image5=#IconsPath#chat.png
Image5Hover=#IconsPath#chat2.png
Image5Text=RaidCall
PathImage5="C:\RaidCall\raidcall.exe"